// Dados compartilhados entre as variações - Guia Prático Portugal
const QUEST_DATA = {
  country: "Portugal",
  flag: "🇵🇹",
  flagColors: ["#046a38", "#da291c"],
  trust: "Confiança média",
  schengen: true,
  updated: "mai/2026",
  totalXP: 2400,
  estimatedTime: "3-6 meses",
  difficulty: 3, // 1-5

  phases: [
    {
      id: "p1",
      number: 1,
      title: "Documentação Essencial",
      subtitle: "Reúna o arsenal antes de partir",
      xp: 800,
      duration: "2-4 semanas",
      difficulty: 2,
      icon: "scroll",
      color: "gold",
      objectives: [
        {
          id: "o1",
          title: "Passaporte válido",
          summary: "Validade mínima de 6 meses após a data de entrada.",
          detail: "Verifique com antecedência — renovação no Brasil pode demorar várias semanas. Confirme também páginas em branco suficientes para vistos.",
          tip: "Renovação online via Polícia Federal é mais rápida.",
          tags: ["Obrigatório", "Brasil"],
        },
        {
          id: "o2",
          title: "Certidão de antecedentes criminais",
          summary: "Emitida pelo DETRAN ou cartório, apostilada pela Convenção de Haia.",
          detail: "Solicite com pelo menos 30 dias de antecedência. A apostila de Haia é feita em cartório autorizado e tem custo separado.",
          tip: "Validade de 90 dias após emissão.",
          tags: ["Obrigatório", "Apostila Haia"],
        },
        {
          id: "o3",
          title: "Seguro saúde internacional",
          summary: "Cobertura mínima de EUR 30.000 exigida na candidatura ao visto D.",
          detail: "Após regularização, acesso ao SNS (Serviço Nacional de Saúde) português. O seguro privado cobre o período de transição.",
          tip: "Compare seguros com cobertura Schengen completa.",
          tags: ["EUR 30.000", "Visto D"],
        },
        {
          id: "o4",
          title: "Comprovante de fundos",
          summary: "Demonstre meios financeiros suficientes para sua estadia.",
          detail: "Geralmente equivalente ao salário mínimo português multiplicado pelos meses de permanência. Para 1 ano: aproximadamente EUR 9.840.",
          tip: "Extratos dos últimos 3 meses + saldo atual.",
          tags: ["Financeiro"],
        },
        {
          id: "o5",
          title: "Comprovante de morada",
          summary: "Contrato de arrendamento ou termo de responsabilidade.",
          detail: "Em Portugal, o comprovante deve estar em seu nome ou ter um termo de responsabilidade emitido por residente legal.",
          tip: "Reserva de Airbnb por 3+ meses costuma ser aceita.",
          tags: ["Em Portugal"],
        },
      ],
    },
    {
      id: "p2",
      number: 2,
      title: "Processo do Visto",
      subtitle: "Dossiê tático no consulado",
      xp: 1000,
      duration: "30-90 dias",
      difficulty: 3,
      icon: "stamp",
      color: "gold",
      objectives: [
        {
          id: "o6",
          title: "Escolher o tipo de visto",
          summary: "Visto D7 (rendimentos), D8 (nômade digital), D2 (empreendedor), D3 (qualificado), Estudo, etc.",
          detail: "Cada tipo tem requisitos específicos. O D7 é popular para aposentados e rendeiros. O D8 foi criado em 2022 para trabalhadores remotos.",
          tip: "Consulte a aba Vistos para ver os 14 tipos monitorados.",
          tags: ["14 tipos"],
        },
        {
          id: "o7",
          title: "Agendar no VFS Global",
          summary: "Submissão do pedido pelo VFS Global em São Paulo, Rio ou Brasília.",
          detail: "Agendamento online. Levar todos os documentos originais + cópias + traduções juramentadas quando aplicável.",
          tip: "Vagas limitadas — agende com 2-3 meses de antecedência.",
          tags: ["VFS Global"],
        },
        {
          id: "o8",
          title: "Pagar taxas consulares",
          summary: "Taxa do visto + taxa de serviço VFS.",
          detail: "Aproximadamente EUR 90 (taxa consular) + cerca de R$ 280 (serviço VFS). Valores podem mudar conforme câmbio.",
          tags: ["EUR 90", "Taxa"],
        },
        {
          id: "o9",
          title: "Aguardar análise",
          summary: "Prazo médio de 60 dias úteis para resposta.",
          detail: "Você pode acompanhar o status pelo portal do VFS Global. Em caso de pedido de documentos adicionais, responda rapidamente.",
          tip: "Não compre passagens definitivas antes da aprovação.",
          tags: ["~60 dias"],
        },
      ],
    },
    {
      id: "p3",
      number: 3,
      title: "Chegada e Regularização",
      subtitle: "Sela o status final em território",
      xp: 600,
      duration: "30-60 dias",
      difficulty: 2,
      icon: "key",
      color: "gold",
      objectives: [
        {
          id: "o10",
          title: "Solicitar NIF",
          summary: "Número de Identificação Fiscal — equivalente ao CPF.",
          detail: "Pode ser obtido nas Finanças. Necessário para abrir conta bancária, alugar imóvel, contratar serviços.",
          tip: "Possível solicitar via procurador antes mesmo de chegar.",
          tags: ["Finanças"],
        },
        {
          id: "o11",
          title: "Agendar AIMA",
          summary: "Agência para a Integração, Migrações e Asilo (substituiu o SEF).",
          detail: "Após chegar, agende sua entrevista no AIMA dentro do prazo do seu visto. É nesta etapa que recebe o título de residência.",
          tip: "Filas longas — agende imediatamente após chegada.",
          tags: ["AIMA", "Ex-SEF"],
        },
        {
          id: "o12",
          title: "Receber Título de Residência",
          summary: "Cartão físico válido por 2 anos, renovável.",
          detail: "Após 5 anos de residência legal, é possível solicitar residência permanente ou cidadania portuguesa.",
          tip: "Cidadania portuguesa = passaporte da União Europeia.",
          tags: ["Recompensa final", "5 anos → cidadania"],
        },
      ],
    },
  ],

  stats: [
    { label: "Entrada sem visto (Schengen)", value: "Sim", note: "Até 90 dias por turismo", tone: "green" },
    { label: "Tipos de visto monitorados", value: "14", note: "12 de relevância direta", tone: "gold" },
    { label: "Work permit exigido", value: "Não", note: "Trabalho permitido sem autorização especial", tone: "green" },
    { label: "Dados atualizados em", value: "mai/2026", note: "Extração automática mensal", tone: "neutral" },
  ],
};

window.QUEST_DATA = QUEST_DATA;
